# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/a02',
                'doc_host': 'https://hgzech.github.io',
                'git_url': 'https://github.com/hgzech/a02',
                'lib_path': 'a02'},
  'syms': {'a02.core': {'a02.core.foo': ('core.html#foo', 'a02/core.py')}}}
